services:
  db:
    image: postgres:13
    container_name: "rs_postgres"
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  redis:
    image: redis:7
    container_name: "rs_redis"
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5
      timeout: 3s

  django:
    container_name: "rs_django"
    build: ./
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers ${GUNICORN_WORKERS} referral_system.wsgi:application"
    volumes:
      - ./:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    container_name: "rs_nginx"
    image: nginx:1.27.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/usr/src/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
  redis_data: