# Generated by Django 5.1.7 on 2025-03-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
